# Use root/example as user/password credentials
version: '3.1'

services:
  #app:
  #  image: node:12.16.2-alpine
  app:
    # Run dockerfile
    container_name: forms-server
    build: . 
    command: ["./wait-for-it.sh", "db:5432", "--", "./docker_entrypoint.sh"]
    volumes: 
      - ./:/app/
      #- ./:/home/app/
    depends_on:
      - db
    ports:
      - 4000:4000

  adminer:
    container_name: forms-database-gui
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: forms-database
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: forms 
    ports:
      - 5432:5432